version: '3'
services: 
    app:
        container_name: splash_images
        restart: always
        build: .
        ports: 
            - '80:8080'
        links: 
            - db
    db:
        container_name: mongodb
        image: mongo
        ports: 
            - '27017:27017'